In [1]:
import numpy as np

In [6]:
x=np.linspace(0,1,44100)
x

array([0.00000000e+00, 2.26762512e-05, 4.53525023e-05, ...,
       9.99954647e-01, 9.99977324e-01, 1.00000000e+00], shape=(44100,))

In [25]:
y=np.sin(2*np.pi*440*x)
y

array([ 0.00000000e+00,  6.26497429e-02,  1.25053344e-01, ...,
       -1.25053344e-01, -6.26497429e-02,  6.27613383e-14], shape=(44100,))

In [26]:
y=y+np.random.normal(0,0.1,44100)
y

array([ 0.2012633 , -0.05755476,  0.10759378, ...,  0.10510235,
       -0.00998185, -0.00879787], shape=(44100,))

In [27]:
y[np.abs(y)<0.2]=0

In [29]:
np.min(y)

np.float64(-1.3608260913072658)