In [1]:
import numpy as np

In [2]:
image=np.random.randint(0,256,(200,200,3))
image

array([[[140, 216, 124],
        [159,  52, 246],
        [232, 220, 207],
        ...,
        [ 44, 118,  90],
        [ 51, 122, 253],
        [219, 151, 175]],

       [[140, 188, 169],
        [ 98, 143,  21],
        [ 40, 234, 108],
        ...,
        [110, 145,  26],
        [157,  12, 224],
        [216, 179,  99]],

       [[ 79, 219, 165],
        [147, 240, 247],
        [188, 108,  52],
        ...,
        [240,  73, 157],
        [204,  89, 158],
        [226, 118, 244]],

       ...,

       [[ 59, 119, 104],
        [196,   6,  94],
        [ 92, 157,  45],
        ...,
        [134, 194, 218],
        [172, 228,  21],
        [238, 188, 149]],

       [[150,  77, 202],
        [218,  87,  35],
        [163,  35, 150],
        ...,
        [101,  58,  60],
        [ 86, 137, 150],
        [114, 168,  64]],

       [[171, 212,  86],
        [ 32, 181, 103],
        [ 11, 183,  59],
        ...,
        [191,  99, 153],
        [238, 116, 128],
        [ 26, 144, 227]]

In [12]:
img=image[50:150,50:150,:]
gray=np.mean(img,axis=2)
gray=gray.astype(int)
inverted_img=255-gray
print(gray)
inverted_img

[[145 206 126 ...  74 191 103]
 [ 49 105 123 ...  73 115 115]
 [204 155  74 ...  77 147 126]
 ...
 [ 82 146 160 ... 125 113  75]
 [148 216 130 ... 186 185  51]
 [137  64 204 ... 137 187 109]]


array([[110,  49, 129, ..., 181,  64, 152],
       [206, 150, 132, ..., 182, 140, 140],
       [ 51, 100, 181, ..., 178, 108, 129],
       ...,
       [173, 109,  95, ..., 130, 142, 180],
       [107,  39, 125, ...,  69,  70, 204],
       [118, 191,  51, ..., 118,  68, 146]], shape=(100, 100))