In [2]:
import numpy as np

In [3]:
#ARRAY OPERATIONS

In [ ]:
#Arithmetic operations

In [13]:
a1=np.arange(1,6)
a2=np.arange(6,11)
a1+a2

array([ 7,  9, 11, 13, 15])

In [14]:
a1-a2

array([-5, -5, -5, -5, -5])

In [15]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [16]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1//a2

array([0, 0, 0, 0, 0])

In [18]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [20]:
#broadcasting

In [22]:
a1+10 #any operation can be performed

array([11, 12, 13, 14, 15])

In [24]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
 #deep and shallow copy

In [26]:
n1=np.arange(1,21)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
slice=n1[:5]
slice

array([1, 2, 3, 4, 5])

In [35]:
slice=slice+10 #due to shallow copy changes will not be reflected to the original array
slice

array([11, 12, 13, 14, 15])

In [36]:
n1 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
n2=n1
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
n2[0]=101 #due to deep copy changes will be reflected to the original array
n2

array([101,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [41]:
n1

array([101,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
#Matrix operations

In [46]:
A=np.arange(1,5).reshape(2,2)
B=np.arange(5,9).reshape(2,2)

In [52]:
A@B  # @ for matrix multiplication

array([[19, 22],
       [43, 50]])

In [49]:
np.dot(A,B)    # Function for array multiplication

array([[19, 22],
       [43, 50]])

In [51]:
A.T         # .T for transposing an array

array([[1, 3],
       [2, 4]])

In [ ]:
# Advance Array Manipulation

In [ ]:
#Stacking Array

In [54]:
l1=np.arange(1,6)
l2=np.arange(2,7)
l3=np.arange(3,8)
np.vstack((l1,l2,l3))

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [55]:
np.hstack((l1,l2,l3))

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7])

In [57]:
np.column_stack((l1,l2))

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [ ]:
#Splitting array

In [59]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]