In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
matrix=np.array(l)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
one=np.ones((6,6))
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
spc=np.linspace(0,1,50)
spc

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [5]:
np.random.randint(1,100,60)

array([52, 77, 24, 89, 71, 37, 76, 15, 65,  1, 73,  7, 29, 53, 47, 52, 38,
       78, 30, 87, 75,  4, 33, 83, 25, 87,  4, 54,  6,  6, 41, 18, 24, 40,
       98, 42, 19, 32, 35, 70, 91, 50, 47, 50, 44, 68, 60, 78, 60, 97, 47,
       88, 63, 65, 11, 34,  6, 78, 59, 71])

In [19]:
np.random.randn(100)

array([-0.31988089,  1.36863432,  0.43569063,  0.62384889,  1.06968448,
       -0.74540934,  0.4744225 ,  0.81981502,  1.3394204 ,  0.33475547,
        0.11143455,  2.57029414,  0.84344665,  0.36912028,  1.87706868,
        1.53627061, -0.09036053, -0.14358903, -1.15237425, -0.07096791,
       -0.02672913,  0.03627384, -1.73536291,  0.57277709, -1.00621881,
        1.942476  , -2.00350809,  0.3250832 , -0.0580106 , -0.46481359,
        0.32873221,  0.946802  , -0.80058451,  1.14788394,  0.8800148 ,
        0.6497635 , -1.15626432, -1.59797339, -1.04356548, -0.08471997,
       -0.4687936 ,  0.03749782, -0.91916574,  0.36573619, -0.20007553,
       -0.30740045, -0.01688136,  2.8570086 , -1.03911055,  1.8648077 ,
       -0.51302486,  0.34252486,  0.82841257, -1.19546294, -0.69998497,
        1.08746022, -0.47370412, -1.06947373,  1.66876094, -0.53432986,
        0.10789937,  0.31407869, -0.44078656,  0.64734135,  1.99212797,
        0.68682319,  1.1841177 ,  0.90319441, -0.05081025,  0.29

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [25]:
np.sum(arr,1)    #gives sum vertically

array([ 6, 15, 24])

In [26]:
np.sum(arr,0)    #gives sum horizontally

array([12, 15, 18])

In [27]:
arr.mean()

np.float64(5.0)

In [28]:
arr.std()

np.float64(2.581988897471611)

In [29]:
arr.argmax()

np.int64(8)

In [30]:
arr.argmin()

np.int64(0)

In [32]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [3]:
 #NUMPY INDEXING AND SLICING OF VECTORS

In [4]:
arr=np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
arr[5]


np.int64(6)

In [12]:
arr[3:9]  #start from 3 and ending is n-1 is not included

array([4, 5, 6, 7, 8, 9])

In [13]:
arr[1:11:2]

array([ 2,  4,  6,  8, 10])

In [14]:
 #NUMPY INDEXING AND SLICING OF MATRIX

In [15]:
arr=np.arange(1,31).reshape(6,5 )
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [28]:
slice=arr[3: ,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
#BOOLEAN INDEXING



arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [36]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [4]:
np.eye(3,dtype='i') 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [5]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])